name: Helm Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:

    if: github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: azure/setup-helm@v1
    - name: Setup Welcome Helm Repo
      run: helm version
